### ISSUE TITLE
consider supporting JRE 6/7

### ISSUE THREAD

**Issue by psacc** [Zlika/reproducible-build-maven-plugin#1]
Have you considered lowering the JRE requirement to 6 or 7 (maybe using retrolambda, just the runtime, not the JDK)?

**Comment by Zlika** [comment]
Hi,
Thank you for your feedback. Currently I do not plan to support older versions of Java because I don't want to bother with their limitations.
The Java 8 requirement only apply to the Java version you use to launch Maven, but you can still configure the Maven build to compile for a Java 6/7 target, so I don't think this is such a big issue anyway.
