### ISSUE TITLE
v1.0?

### ISSUE THREAD

**Issue by fndejong** [Zlika/reproducible-build-maven-plugin#11]
Hello all,

Can the current version of the plugin be considered stable? If not, is there a roadmap up to v1.0?

While trying to fix [this](https://issues.jboss.org/browse/SWARM-1414) concerning idem-potency builds for [Wildfly Swarm](http://wildfly-swarm.io/) I came across this neat plugin and it worked instantly! So I already proposed it to the Wildfly-Swarm team, but I guess (as an outsider) there needs to be a certain level of trust before I can integrate this plugin with the Wildfly Swarm Maven Plugin.

**Comment by Zlika** [comment]
Hi,

The current version is stable, feel free to use it on Swarm. It is used inside my company, and I known it's also used in the Apache Beam project.
If you want to use it to build another Maven plugin, you may be impacted by [MPLUGIN-261](https://issues.apache.org/jira/browse/MPLUGIN-261) depending on the version of maven-archiver used during the build (issue was fixed in maven-archiver-3.0.1). I plan to manage this bug in the next version of reproducible-build-maven-plugin so that we don't have to bother on the version of maven-archiver.
