### ISSUE TITLE
Split into library and maven plugin

### ISSUE THREAD

**Issue by raboof** [Zlika/reproducible-build-maven-plugin#8]
Would you be open to the idea of splitting the reproducible-build-maven-plugin into a 'maven plugin' part and a 'library' part?

I hacked up an [sbt-reproducible-builds](https://github.com/raboof/sbt-reproducible-builds) plugin just by wrapping the reproducible-build-maven-plugin strippers, and while I'm sure this is not completely sufficient, it's already looking quite promising. Right now I just depend on the reproducible-build-maven-plugin, it would of course be a bit neater to depend on a "reproducible-build" library that contains the core of the plugin and can be shared among various build systems.

I'd be happy to help!

**Comment by Zlika** [comment]
Hi!
Thank you for your proposal. I don't use scala at all but I'd be glad if my work can also help the scala community.
Right now I think that splitting the project in two would bring too much complexity for such a small code base. I merged your pull request #7 so that you can use reproducible-build-maven-plugin as a dependency of your sbt plugin, but I understand that it's not so great to download maven-specific dependencies for a sbt plugin.
A workaround would be to exclude the maven-specific plugins (i.e. maven-plugin-api, maven-plugin-annotations, plexus-utils and their transitive dependencies, in fact the stripper classes only use commons-compress as a dependency) when you include reproducible-build-maven-plugin (it's easy to do so with maven, so it must be also easy to do the same with sbt).
Let me know your opinion, and also if you have scala-specific sources of non-reproduciblity I'm open to include the required strippers in the code base (it would certainly help people with polyglot source code using maven to compile everything).
Regards

**Comment by raboof** [comment]
I could indeed exclude the transitive dependencies that are not needed in my context.

However, unfortunately this is not my only problem: because reproducible-build-maven-plugin is packaged as a `maven-plugin`, it cannot be added as a dependency without explicitly telling sbt to also allow dependencies of packaging `maven-plugin`. If that was needed just for building my sbt plugin that wouldn't be an issue, but unfortunately users of the plugin also need to add it for the transitive dependency to be resolvable.

Luckily, it appears there's a fairly lightweight solution: it looks like we could add a second `pom.xml` (say, `pom-standalone.xml`) to this project to package the same sources both as a maven-plugin and as a normal jar. What do you think?

**Comment by Zlika** [comment]
I'm not very fond of this workaround either... Can we take some time to think about it, or is it a blocking problem for you?

**Comment by raboof** [comment]
I'll probably publish from my own branch in the mean time then, but if you have any other ideas I'd be happy to collaborate on them!

**Comment by Zlika** [comment]
Another idea for you to reuse parts of the reproducible-maven-plugin code without the maven plumbing: could you do something similar to http://maven.apache.org/plugins/maven-dependency-plugin/examples/unpacking-artifacts.html with sbt?
